### ISSUE TITLE
Ring mount

### ISSUE THREAD

**Issue by poldim** [xs4free/progz.nl-homeautomation#3]
I found this while looking for a way to know that I was on a teams call. I’m wondering if I can do what you did considering I use a corporate sso account on a custom domain and am on a Mac. 

BTW, check out this for a great ring mount  https://www.thingiverse.com/thing:4594797 for your ring LED.

**Comment by poldim** [comment]
Found this for anyone else looking: https://github.com/kancelott/msteams-presence-led/tree/master

**Comment by xs4free** [comment]
Hi @poldim,

I'm currently using my app on a custom corporate domain, it's not fully SSO but I expect that doesn't matter for this code.

Thanks for the links! The led-ring mount looks very nice. In my use-case I want to mount the led-ring outside my room so my daughter can see my status before entering the room, and for that use-case this design is way to bulky and difficult to mount. But I would definitely consider using this mount if I want to use a ring inside my room.

The other link is also interesting, I will consider implementing this detection method as a second option inside my program once I looked at the details of the logfile. I'm curious if it will detected a meeting on your phone and I'm a bit worried that the logging format might change in the future since Teams is getting regular updates lately. But it's an interesting approach!

Thanks for sharing and replying!
